### PR TITLE
Allow requesting multiple inverter properties at once and simplify access to them

### PR DESCRIPTION
**Pull request by scheidtdav**
Hey @DAMEK86 ,

it's been some time :grimacing: 
I finally had some time with this again and figured I should add whats missing.

Here is a quick breakdown:
- The values in `const.py` are now classes which simplifies accessing them via their names (you also get nice intellisense in VS Code)
- I replace `__fetch_dxs_entries` with a `fetch_props` method to allow users of the library to fetch multiple values in one go
- The inverter class also returns DxsEntry objects now. This should be much easier to include into Home Assistant since individual sensors need a unique id (which can be the DxsId). Previously only the value was returned

Hope these changes are fine for you! Would love to hear your feedback :)

### CODE REVIEW

**Comment by DAMEK86** [comment]
hey, sorry for the late response.
with the class approach, it's possible to provide methods like generating a list of the whole domain. That's cool!

In the case of OOP it would be smarter to move the methods inside the classes and/or provide a base class with the generic call and then provide the domains as a property of inverter :thinking: 
Then it's easy to extend the classes by context and functionality.
Furthermore, the lib user can write code like `inverter.actualBattery.get/fetch(...)` or `inverter.actualBattery.get/fetch_all()`.

I also understand your approach. the Inverter class is fine but there are too many functions within one class which make it ticky to maintain in case of backward compatibility.

**Suggestion**
```
class ActualAnalogInputs:
    ANALOG1 = 167772417
    ANALOG2 = 167772673
    ANALOG3 = 167772929
    ANALOG4 = 167773185

    def __init__(self, inverter:Piko):
      self.__inverter =  inverter

    async def analog_1(self) -> DxsEntry:
        return (await self.__inverter.fetch_props(ANALOG1)) \
            .get_entry_by_id(ANALOG1)

    async def analog_2(self) -> DxsEntry:
        return (await self.__inverter.fetch_props(ANALOG2)) \
            .get_entry_by_id(ANALOG2)

    async def analog_3(self) -> DxsEntry:
        return (await self.__inverter.fetch_props(ANALOG3)) \
            .get_entry_by_id(ANALOG3)

    async def analog_4(self) -> DxsEntry:
        return (await self.__inverter.fetch_props(ANALOG4)) \
            .get_entry_by_id(ANALOG4)
```

Not quite sure if this is the best solution but extending these classes with additional methods is really easy in the future.
The most important thing is backward compatibility. You can encapsulate the getter code - okay, the Piko class still needs the same API but adding additional methods are also easy :)

what do you think @scheidtdav

**Comment by scheidtdav** [comment]
Hey, no worries about the delay.

Absolutely agree on utilizing OOP more. 
I could implement your suggestion.

One question regarding backward compatibility though:
As of now, the inverter only had the day_yield method implemented. If we drop this, we could easily go with the approach you mentioned (`inverter.actualBattery.fetchXYZ()`) and entirely skip having `fetchXYZ()` in the inverter.
I'd argue thats easy enough to use.

However I would always keep the new `fetch_props` method, so you can batch request a bunch (but not necessarily all) of the properties of several domains.

**Comment by DAMEK86** [comment]
yeah. sounds nice. `day_yield` was only for verification. :rofl:
I'm totally fine. I prefer to provide the generic method `fetch_props` inside the converter as well.

thx for your work!!!

**Comment by scheidtdav** [comment]
Ok good, was kind of expecting `day_yield` to be just for verification.
I did a little refactoring, please check again :) 

Is this how you were imagining this?
I did not add an additional `fetchall` to each domain for the moment. That would be a new feature for a future version imho, but certainly a nice one.

Also pls provide feedback to the coding style if any, I am not too deep into python development and the coding guidelines etc.
Happy to adjust accordingly :+1:

**Pull request merged**
